services:
  web:
    build: ./st_web
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      TRANSLATOR_PROVIDER: deepl
      API_URL: "http://backend:8081"
      OLLAMA_SERVER: "http://ollama:11434"
    depends_on:
      - backend
    networks:
      - mynet

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      LLM_PROVIDER: groq
      LLM_MODEL: llama3-70b-8192
      LLM_API_TOKEN: "your-api-token-here"
      OLLAMA_SERVER: "http://ollama:11434"
    depends_on:
      - db
    networks:
      - mynet

  db:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /data/redis-data:/data
    networks:
      - mynet
    
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ./ollama:/root/.ollama:rw

networks:
  mynet:
    driver: bridge