services:
  web:
    build: ./st_web
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      TRANSLATOR_PROVIDER: deepl
      API_URL: "http://backend:8081"
    depends_on:
      - backend
    networks:
      - mynet

  backend:
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      LLM_PROVIDER: groq
      LLM_MODEL: llama3-70b-8192
      LLM_API_TOKEN: "your-api-token-here"
    depends_on:
      - db
    networks:
      - mynet

  db:
    restart: always
    image: redis:lastest
    ports:
      - "6379:6379"
    volumes:
      - /data/redis-data:/data
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge